# Generated by Django 5.1.2 on 2024-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato (00) 0000-0000', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='residente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato (00) 0000-0000', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
