# Generated by Django 4.2.16 on 2024-11-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Inicio'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
