# Generated by Django 5.1.2 on 2024-10-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_administrador_telefone_residente_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato (00) 00000-0000', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='residente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato (00) 00000-0000', max_length=11, verbose_name='Telefone'),
        ),
    ]
