# Generated by Django 5.1.2 on 2024-10-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_alter_administrador_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='celular',
            field=models.CharField(blank=True, help_text='Formato (00) 00000-0000', max_length=11, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato (00) 0000-0000', max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='telefone_comercial',
            field=models.CharField(blank=True, help_text='Formato (00) 0000-0000', max_length=11, verbose_name='Tel. Comercial'),
        ),
    ]
