# Generated by Django 4.2.16 on 2024-10-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0014_endereco_responsavel_responsavel_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
