# Generated by Django 4.2.16 on 2024-12-03 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0022_alter_atividade_capacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='inscritos',
            field=models.ManyToManyField(blank=True, related_name='atividades_inscritas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='capacidade',
            field=models.IntegerField(blank=True, help_text='', null=True, verbose_name='Capacidade'),
        ),
    ]
